version: "3"

services:
  spark-notebook:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grandata_spark
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data
      - ./output:/home/jovyan/output
