version: "3"

services:
  spark-notebook:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grandata_spark
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/workspace/notebooks
      - ./data:/workspace/data
      - ./output:/workspace/output
    working_dir: /workspace
    command: >
      jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token= --NotebookApp.password=
